<#
.SYNOPSIS
    Normalizes audio files generated by asbplayer for Anki mining.
.DESCRIPTION
    A configurable PowerShell script that uses FFmpeg to batch-normalize
    audio files in an Anki media directory.
.PARAMETER TodayOnly
    If specified, only processes files created today that match the asbplayer filter.
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [switch]$TodayOnly
)

# 1. Load Configurations
$ConfigFile = Join-Path $PSScriptRoot "config.json"
if (-not (Test-Path $ConfigFile)) {
    Write-Error "Configuration file 'config.json' not found at $ConfigFile"
    exit 1
}

$Config = Get-Content -Raw $ConfigFile | ConvertFrom-Json
$MediaDir = $Config.MediaDirectory

# Verify Media Directory exists
if (-not (Test-Path $MediaDir)) {
    Write-Error "Anki media directory not found at: $MediaDir. Please check config.json."
    exit 1
}

# 2. Define File Targeting Strategy
$FilesToProcess = @()

if ($TodayOnly) {
    # Match the behavior of your original "today" script
    Write-Host "Mode: Processing TODAY'S asbplayer audio files only." -ForegroundColor Cyan
    $MidnightToday = (Get-Date).Date
    $FilesToProcess = Get-ChildItem -Path $MediaDir -Filter $Config.AsbPlayerFilter |
        Where-Object { $_.CreationTime -ge $MidnightToday }
} else {
    # Match the behavior of your original "all" script
    Write-Host "Mode: Processing ALL configured audio extensions." -ForegroundColor Cyan
    foreach ($Ext in $Config.FileExtensions) {
        $FilesToProcess += Get-ChildItem -Path $MediaDir -Filter $Ext
    }
}

if ($FilesToProcess.Count -eq 0) {
    Write-Host "No matching audio files found to process." -ForegroundColor Yellow
    Write-Host "Done!"
    exit 0
}

Write-Host "Found $($FilesToProcess.Count) file(s) to process.`n" -ForegroundColor Green

# 3. Process Audio Files
foreach ($File in $FilesToProcess) {
    $InputPath = $File.FullName
    $TempPath  = $InputPath + ".tmp.mp3"

    Write-Host "Normalizing: $($File.Name)" -ForegroundColor White

    # Run FFmpeg with settings pulled from config.json
    & ffmpeg -i $InputPath `
             -af $Config.FFmpegSettings.AudioFilter `
             -ar $Config.FFmpegSettings.AudioRate `
             -b:a $Config.FFmpegSettings.Bitrate `
             $TempPath -y -loglevel quiet

    # If FFmpeg succeeded and generated the temp file, swap it with the original
    if (Test-Path $TempPath) {
        Remove-Item $InputPath -Force
        Rename-Item $TempPath $InputPath
    } else {
        Write-Warning "Failed to process: $($File.Name)"
    }
}

Write-Host "`nDone!" -ForegroundColor Green
