<#
.SYNOPSIS
    Normalizes audio files generated by asbplayer for Anki mining.
.DESCRIPTION
    A configurable PowerShell script that uses FFmpeg to batch-normalize
    audio files in an Anki media directory.
.PARAMETER TodayOnly
    If specified, only processes files created today that match the asbplayer filter.
.PARAMETER All
    If specified, processes all asbplayer audio files without prompting.
.PARAMETER Preview
    Lists matching files without processing them.
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [switch]$TodayOnly,

    [Parameter(Mandatory = $false)]
    [switch]$All,

    [Parameter(Mandatory = $false)]
    [switch]$Preview
)

if ($TodayOnly -and $All) {
    Write-Error "Use either -TodayOnly or -All, not both."
    exit 1
}

# 1. Load Configurations
$ConfigFile = Join-Path $PSScriptRoot "config.json"
if (-not (Test-Path $ConfigFile)) {
    Write-Error "Configuration file 'config.json' not found at $ConfigFile"
    exit 1
}

$Config = Get-Content -Raw $ConfigFile | ConvertFrom-Json
$MediaDir = $Config.MediaDirectory

if ([string]::IsNullOrWhiteSpace($MediaDir) -or $MediaDir -match '<[^>]+>') {
    Write-Error "MediaDirectory is still using a placeholder value. Open config.json and replace it with your real Anki collection.media path."
    exit 1
}

# Verify Media Directory exists
if (-not (Test-Path $MediaDir)) {
    Write-Error "Anki media directory not found at: $MediaDir. Please check config.json."
    exit 1
}

$AsbPlayerFilter = $Config.AsbPlayerFilter
if ([string]::IsNullOrWhiteSpace($AsbPlayerFilter)) {
    Write-Error "AsbPlayerFilter is missing from config.json."
    exit 1
}

$FFmpegCommand = Get-Command ffmpeg -ErrorAction SilentlyContinue
if (-not $FFmpegCommand) {
    Write-Error "FFmpeg was not found on PATH. Install FFmpeg and make sure the folder containing ffmpeg.exe is added to PATH, then open a new PowerShell window and try again."
    exit 1
}

# 2. Define File Targeting Strategy
$FilesToProcess = @()

$ProcessTodayOnly = $TodayOnly
if (-not $TodayOnly -and -not $All) {
    Write-Host "Choose what to process:" -ForegroundColor Cyan
    Write-Host "  [A] All configured audio files"
    Write-Host "  [T] Today's asbplayer audio files only"
    $Choice = Read-Host "Enter A or T"

    if ($Choice -match '^[Tt]') {
        $ProcessTodayOnly = $true
    } elseif ($Choice -match '^[Aa]$' -or [string]::IsNullOrWhiteSpace($Choice)) {
        $ProcessTodayOnly = $false
    } else {
        Write-Error "Invalid selection. Enter A for all files or T for today only."
        exit 1
    }
}

if ($ProcessTodayOnly) {
    # Match the behavior of your original "today" script
    Write-Host "Mode: Processing TODAY'S asbplayer audio files only." -ForegroundColor Cyan
    $MidnightToday = (Get-Date).Date
    foreach ($Ext in $Config.FileExtensions) {
        $FilesToProcess += Get-ChildItem -Path $MediaDir -Filter $Ext |
            Where-Object { $_.Name -like $AsbPlayerFilter -and $_.CreationTime -ge $MidnightToday }
    }
} else {
    # Match the behavior of your original "all" script
    Write-Host "Mode: Processing ALL asbplayer audio files." -ForegroundColor Cyan
    foreach ($Ext in $Config.FileExtensions) {
        $FilesToProcess += Get-ChildItem -Path $MediaDir -Filter $Ext |
            Where-Object { $_.Name -like $AsbPlayerFilter }
    }
}

if ($FilesToProcess.Count -eq 0) {
    Write-Host "No matching audio files found to process." -ForegroundColor Yellow
    Write-Host "Done!"
    exit 0
}

Write-Host "Found $($FilesToProcess.Count) file(s) to process.`n" -ForegroundColor Green

if ($Preview) {
    $FilesToProcess | Select-Object -ExpandProperty Name
    Write-Host "`nPreview only. No files were processed." -ForegroundColor Yellow
    exit 0
}

# 3. Process Audio Files
foreach ($File in $FilesToProcess) {
    $InputPath = $File.FullName
    $TempPath  = $InputPath + ".tmp.mp3"

    Write-Host "Normalizing: $($File.Name)" -ForegroundColor White

    # Run FFmpeg with settings pulled from config.json
    & $FFmpegCommand.Source -i $InputPath `
             -af $Config.FFmpegSettings.AudioFilter `
             -ar $Config.FFmpegSettings.AudioRate `
             -b:a $Config.FFmpegSettings.Bitrate `
             $TempPath -y -loglevel quiet

    # If FFmpeg succeeded and generated the temp file, swap it with the original
    if (Test-Path $TempPath) {
        Remove-Item $InputPath -Force
        Rename-Item $TempPath $InputPath
    } else {
        Write-Warning "Failed to process: $($File.Name)"
    }
}

Write-Host "`nDone!" -ForegroundColor Green
